init_config:

instances:
  - name: mysql_router_rw
    host: mysql-router
    port: 6446
    timeout: 2
    tags:
      - service:mysql-router
      - route:rw
  - name: mysql_router_ro
    host: mysql-router
    port: 6447
    timeout: 2
    tags:
      - service:mysql-router
      - route:ro
