init_config:

ad_identifiers:
  - mongo

instances:
  - hosts:
      - "%%host%%:27017"
    tags:
      - "hostname:adamic-wsl2"
    reported_hostname: adamic-wsl2

logs:
  - source: mongodb
    service: mongo-server
