/**
 * Server instructions for mysql-mcp (MySQL MCP Server).
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/instructions/markdown/*.md instead,
 *     then run: npm run generate:instructions
 */

export { INSTRUCTIONS } from "./instructions/base.js";

import { ADMIN_HELP } from "./instructions/admin.js";
import { BACKUP_HELP } from "./instructions/backup.js";
import { CLUSTER_HELP } from "./instructions/cluster.js";
import { CODEMODE_HELP } from "./instructions/codemode.js";
import { CORE_HELP } from "./instructions/core.js";
import { DOCSTORE_HELP } from "./instructions/docstore.js";
import { EVENTS_HELP } from "./instructions/events.js";
import { FULLTEXT_HELP } from "./instructions/fulltext.js";
import { GOTCHAS_HELP } from "./instructions/gotchas.js";
import { INTROSPECTION_HELP } from "./instructions/introspection.js";
import { JSON_HELP } from "./instructions/json.js";
import { MIGRATION_HELP } from "./instructions/migration.js";
import { MONITORING_HELP } from "./instructions/monitoring.js";
import { OPTIMIZATION_HELP } from "./instructions/optimization.js";
import { PARTITIONING_HELP } from "./instructions/partitioning.js";
import { PERFORMANCE_HELP } from "./instructions/performance.js";
import { PROXYSQL_HELP } from "./instructions/proxysql.js";
import { REPLICATION_HELP } from "./instructions/replication.js";
import { ROLES_HELP } from "./instructions/roles.js";
import { ROUTER_HELP } from "./instructions/router.js";
import { SCHEMA_HELP } from "./instructions/schema.js";
import { SECURITY_HELP } from "./instructions/security.js";
import { SHELL_HELP } from "./instructions/shell.js";
import { SPATIAL_HELP } from "./instructions/spatial.js";
import { STATS_HELP } from "./instructions/stats.js";
import { SYSSCHEMA_HELP } from "./instructions/sysschema.js";
import { TEXT_HELP } from "./instructions/text.js";
import { TRANSACTIONS_HELP } from "./instructions/transactions.js";
import { VECTOR_HELP } from "./instructions/vector.js";

export const HELP_CONTENT: ReadonlyMap<string, string> = new Map([
  ["admin", ADMIN_HELP],
  ["backup", BACKUP_HELP],
  ["cluster", CLUSTER_HELP],
  ["codemode", CODEMODE_HELP],
  ["core", CORE_HELP],
  ["docstore", DOCSTORE_HELP],
  ["events", EVENTS_HELP],
  ["fulltext", FULLTEXT_HELP],
  ["gotchas", GOTCHAS_HELP],
  ["introspection", INTROSPECTION_HELP],
  ["json", JSON_HELP],
  ["migration", MIGRATION_HELP],
  ["monitoring", MONITORING_HELP],
  ["optimization", OPTIMIZATION_HELP],
  ["partitioning", PARTITIONING_HELP],
  ["performance", PERFORMANCE_HELP],
  ["proxysql", PROXYSQL_HELP],
  ["replication", REPLICATION_HELP],
  ["roles", ROLES_HELP],
  ["router", ROUTER_HELP],
  ["schema", SCHEMA_HELP],
  ["security", SECURITY_HELP],
  ["shell", SHELL_HELP],
  ["spatial", SPATIAL_HELP],
  ["stats", STATS_HELP],
  ["sysschema", SYSSCHEMA_HELP],
  ["text", TEXT_HELP],
  ["transactions", TRANSACTIONS_HELP],
  ["vector", VECTOR_HELP],
]);
