/**
 * Method aliases for code mode API.
 * Maps alternate method names to their canonical method names.
 * Format: { groupName: { aliasName: canonicalName } }
 *
 * These aliases handle common naming misguesses where agents
 * might try the redundant prefix pattern (e.g., jsonExtract vs extract).
 */
export const METHOD_ALIASES: Record<string, Record<string, string>> = {
  // JSON: mysql_json_extract → extract, but agent might try jsonExtract
  json: {
    jsonExtract: "extract",
    jsonSet: "set",
    jsonInsert: "insert",
    jsonRemove: "remove",
    jsonContains: "contains",
    jsonKeys: "keys",
    jsonReplace: "replace",
    jsonGet: "get",
    jsonSearch: "search",
    jsonUpdate: "update",
    jsonValidate: "validate",
    validateData: "validate",
    jsonMerge: "merge",
    mergeJson: "merge",
    jsonNormalize: "normalize",
    normalizeJson: "normalize",
    jsonDiff: "diff",
    diffJson: "diff",
    jsonIndexSuggest: "indexSuggest",
    index: "indexSuggest",
    suggest: "indexSuggest",
    jsonStats: "stats",
    info: "stats",
    jsonArrayAppend: "arrayAppend",
    append: "arrayAppend",
  },
  // Text: mysql_regexp_match → regexpMatch, but also regex
  text: {
    regex: "regexpMatch",
    regexp: "regexpMatch",
    like: "likeSearch",
    pattern: "likeSearch",
    sound: "soundex",
    substr: "substring",
    concatenate: "concat",
    collation: "collationConvert",
    get: "likeSearch",
    search: "likeSearch",
    find: "likeSearch",
    match: "regexpMatch",
    sub: "substring",
  },
  // Fulltext: intuitive aliases
  fulltext: {
    create: "fulltextCreate",
    add: "fulltextCreate",
    drop: "fulltextDrop",
    remove: "fulltextDrop",
    delete: "fulltextDrop",
    search: "fulltextSearch",
    get: "fulltextSearch",
    find: "fulltextSearch",
    boolean: "fulltextBoolean",
    expand: "fulltextExpand",
    createIndex: "fulltextCreate",
    dropIndex: "fulltextDrop",
    naturalLanguage: "fulltextSearch",
    booleanMode: "fulltextBoolean",
    queryExpansion: "fulltextExpand",
  },
  // Transactions: shorter aliases
  transactions: {
    begin: "transactionBegin",
    start: "transactionBegin",
    commit: "transactionCommit",
    end: "transactionCommit",
    rollback: "transactionRollback",
    cancel: "transactionRollback",
    stop: "transactionRollback",
    savepoint: "transactionSavepoint",
    createSavepoint: "transactionSavepoint",
    addSavepoint: "transactionSavepoint",
    release: "transactionRelease",
    releaseSavepoint: "transactionRelease",
    removeSavepoint: "transactionRelease",
    dropSavepoint: "transactionRelease",
    rollbackTo: "transactionRollbackTo",
    rollbackToSavepoint: "transactionRollbackTo",
    revertToSavepoint: "transactionRollbackTo",
    execute: "transactionExecute",
  },
  performance: {
    mysql_explain: "explain",
    mysql_explain_analyze: "explainAnalyze",
    mysql_slow_queries: "slowQueries",
    queryPlan: "explain",
    analyze: "explainAnalyze",
    slowLog: "slowQueries",
    slow: "slowQueries",
    trace: "optimizerTrace",
    bufferPool: "bufferPoolStats",
    stats: "tableStats",
    table: "tableStats",
    threads: "threadStats",
    queries: "queryStats",
    slowlog: "slowQueries",
    index: "indexUsage",
    indexes: "indexUsage",
    usage: "indexUsage",
    detectAnomalies: "detectQueryAnomalies",
    anomalies: "detectQueryAnomalies",
    queryAnomalies: "detectQueryAnomalies",
    bloatRisk: "detectBloatRisk",
    bloat: "detectBloatRisk",
    detectBloat: "detectBloatRisk",
    connectionSpike: "detectConnectionSpike",
    spikes: "detectConnectionSpike",
    connections: "detectConnectionSpike",
    get: "tableStats",
  },
  // Optimization: shorter aliases
  optimization: {
    recommend: "indexRecommendation",
    indexAdvice: "indexRecommendation",
    hint: "forceIndex",
    forceHint: "forceIndex",
    rewrite: "queryRewrite",
    get: "indexRecommendation",
    mysql_force_index: "forceIndex",
    mysql_optimizer_trace: "optimizerTrace",
  },
  // Admin: intuitive aliases
  admin: {
    check: "checkTable",
    repair: "repairTable",
    optimize: "optimizeTable",
    analyze: "analyzeTable",
    flush: "flushTables",
    kill: "killQuery",
    serverConfig: "serverConfig",
    config: "serverConfig",
    insight: "appendInsight",
    append: "appendInsight",
    audit: "auditSearch",
    search: "auditSearch",
  },
  // Monitoring: intuitive aliases
  monitoring: {
    status: "showStatus",
    variables: "showVariables",
    processes: "showProcesslist",
    processlist: "showProcesslist",
    innodb: "innodbStatus",
    health: "serverHealth",
    pool: "poolStats",
    get: "serverHealth",
    replication: "replicationStatus",
    mysql_innodb_status: "innodbStatus",
    mysql_replication_status: "replicationStatus",
    mysql_pool_stats: "poolStats",
    mysql_show_status: "showStatus",
    mysql_show_variables: "showVariables",
    mysql_show_processlist: "showProcesslist",
    mysql_server_health: "serverHealth",
  },
  // Backup: shorter aliases
  backup: {
    dump: "createDump",
    export: "exportTable",
    import: "importData",
    restore: "restoreDump",
    mysql_export_table: "exportTable",
    mysqlExportTable: "exportTable",
    mysql_import_data: "importData",
    mysqlImportData: "importData",
    mysql_create_dump: "createDump",
    mysqlCreateDump: "createDump",
    mysql_restore_dump: "restoreDump",
    mysqlRestoreDump: "restoreDump",
    list: "auditListBackups",
    auditList: "auditListBackups",
    mysql_audit_list_backups: "auditListBackups",
    mysqlAuditListBackups: "auditListBackups",
    mysql_audit_restore_backup: "auditRestoreBackup",
    mysqlAuditRestoreBackup: "auditRestoreBackup",
    auditRestore: "auditRestoreBackup",
    auditDiff: "auditDiffBackup",
    diff: "auditDiffBackup",
  },
  // Replication: intuitive aliases
  replication: {
    status: "slaveStatus",
    master: "masterStatus",
    slave: "slaveStatus",
    binlog: "binlogEvents",
    gtid: "gtidStatus",
    lag: "replicationLag",
    getLag: "replicationLag",
    get: "slaveStatus",
    info: "slaveStatus",
  },
  // Partitioning: shorter aliases
  partitioning: {
    add: "addPartition",
    drop: "dropPartition",
    remove: "dropPartition",
    delete: "dropPartition",
    reorganize: "reorganizePartition",
    info: "partitionInfo",
    list: "partitionInfo", // list() → partitionInfo()
    get: "partitionInfo",
  },
  // Schema: intuitive aliases
  schema: {
    views: "listViews",
    getViews: "listViews",
    getView: "listViews",
    addView: "createView",
    removeView: "dropView",
    functions: "listFunctions",
    getFunctions: "listFunctions",
    procedures: "listStoredProcedures",
    getStoredProcedures: "listStoredProcedures",
    triggers: "listTriggers",
    getTriggers: "listTriggers",
    events: "listEvents",
    getEvents: "listEvents",
    constraints: "listConstraints",
    schemas: "listSchemas",
    createDb: "createSchema",
    dropDb: "dropSchema",
    list: "listSchemas",
    get: "listSchemas",
    create: "createSchema",
    drop: "dropSchema",
  },
  // Events: shorter aliases
  events: {
    create: "eventCreate",
    drop: "eventDrop",
    alter: "eventAlter",
    list: "eventList",
    getAll: "eventList",
    status: "eventStatus",
    get: "eventStatus",
    scheduler: "schedulerStatus",
    getScheduler: "schedulerStatus",
    getSchedulerStatus: "schedulerStatus",
  },
  // Stats: intuitive aliases
  stats: {
    percentile: "percentiles",
    movingAverage: "movingAvg",
    time_series: "timeSeries",
    ts: "timeSeries",
    dist: "distribution",
    desc: "descriptive",
    reg: "regression",
    corr: "correlation",
    hist: "histogram",
    getDescriptive: "descriptive",
    getPercentiles: "percentiles",
    getCorrelation: "correlation",
    getDistribution: "distribution",
    getTimeSeries: "timeSeries",
    getSampling: "sampling",
    getRegression: "regression",
    getHistogram: "histogram",
    getRowNumber: "rowNumber",
    getRank: "rank",
    getLagLead: "lagLead",
    getRunningTotal: "runningTotal",
    getMovingAvg: "movingAvg",
    getNtile: "ntile",
    getHypothesis: "hypothesis",
    getOutliers: "outliers",
    getTopN: "topN",
    getDistinct: "distinct",
    getFrequency: "frequency",
    getSummary: "summary",
    sample: "sampling",
    row_number: "rowNumber",
    statsHistogram: "histogram",
    statsRowNumber: "rowNumber",
    statsSampling: "sampling",
  },
  // Spatial: intuitive aliases
  spatial: {
    addColumn: "createColumn",
    addIndex: "createIndex",
    create: "createColumn",
    dist: "distance",
    distSphere: "distanceSphere",

    pointInPolygon: "contains",
    getPoint: "point",
    get: "polygon",
    getPolygon: "polygon",
    intersect: "intersection",
    getBuffer: "buffer",
    createBuffer: "buffer",
    transformGeometry: "transform",
    convertGeojson: "geojson",
    toGeojson: "geojson",
    fromGeojson: "geojson",
  },
  // Security: intuitive aliases
  security: {
    ssl: "sslStatus",
    encryption: "encryptionStatus",
    firewall: "firewallStatus",
    privileges: "userPrivileges",
    password: "passwordValidate",
    mask: "maskData",
    sensitive: "sensitiveTables",
    auditLog: "audit",
    get: "audit",
  },
  // Cluster: intuitive aliases
  cluster: {
    status: "clusterStatus",
    get: "clusterStatus",
    instances: "clusterInstances",
    topology: "clusterTopology",
    switchover: "clusterSwitchover",
    routerStatus: "clusterRouterStatus",
    members: "grMembers",
    primary: "grPrimary",
    transactions: "grTransactions",
    flowControl: "grFlowControl",
    getPrimary: "grPrimary",
    getMembers: "grMembers",
    getStatus: "grStatus",
    getTransactions: "grTransactions",
    getFlowControl: "grFlowControl",
    getTopology: "clusterTopology",
    getInstances: "clusterInstances",
    getRouterStatus: "clusterRouterStatus",
    getSwitchover: "clusterSwitchover",
    failover: "clusterSwitchover",
    mysql_gr_status: "grStatus",
    mysql_gr_members: "grMembers",
    mysql_gr_primary: "grPrimary",
    mysql_gr_transactions: "grTransactions",
    mysql_gr_flow_control: "grFlowControl",
    mysql_cluster_status: "clusterStatus",
    mysql_cluster_instances: "clusterInstances",
    mysql_cluster_topology: "clusterTopology",
    mysql_cluster_router_status: "clusterRouterStatus",
    mysql_cluster_switchover: "clusterSwitchover",
  },
  // Roles: shorter aliases
  roles: {
    create: "roleCreate",
    drop: "roleDrop",
    list: "roleList",
    assign: "roleAssign",
    grant: "roleGrant",
    revoke: "roleRevoke",
    removeRole: "roleRevoke",
    remove: "roleRevoke",
    grants: "roleGrants",
    get: "roleGrants",
    user: "userRoles",
    getRoles: "userRoles",
  },
  // Migration: shorter aliases
  migration: {
    getHistory: "history",
    get: "history",
    log: "history",
    getStatus: "status",
    info: "status",
    revert: "rollback",
    undo: "rollback",
  },
  // DocStore: shorter aliases
  docstore: {
    add: "docAdd",
    insert: "docAdd",
    find: "docFind",
    modify: "docModify",
    update: "docModify",
    remove: "docRemove",
    delete: "docRemove",
    createCollection: "docCreateCollection",
    create: "docCreateCollection",
    dropCollection: "docDropCollection",
    drop: "docDropCollection",
    listCollections: "docListCollections",
    list: "docListCollections",
    collectionInfo: "docCollectionInfo",
    info: "docCollectionInfo",
    get: "docFind",
    createIndex: "docCreateIndex",
    addIndex: "docCreateIndex",
  },
  // SysSchema: shorter aliases
  sysschema: {
    schemaStats: "sysSchemaStats",
    lockWaits: "sysInnodbLockWaits",
    innodbLockWaits: "sysInnodbLockWaits",
    memory: "sysMemorySummary",
    memorySummary: "sysMemorySummary",
    statements: "sysStatementSummary",
    statementSummary: "sysStatementSummary",
    waits: "sysWaitSummary",
    waitSummary: "sysWaitSummary",
    io: "sysIoSummary",
    ioSummary: "sysIoSummary",
    users: "sysUserSummary",
    userSummary: "sysUserSummary",
    hosts: "sysHostSummary",
    hostSummary: "sysHostSummary",
    get: "sysSchemaStats",
    getUsers: "sysUserSummary",
    getHosts: "sysHostSummary",
    getStatements: "sysStatementSummary",
    getWaits: "sysWaitSummary",
    getIo: "sysIoSummary",
    getMemory: "sysMemorySummary",
    getLocks: "sysInnodbLockWaits",
    stats: "sysSchemaStats",
    info: "sysSchemaStats",
  },
  // Router: shorter aliases
  router: {
    metadata: "metadataStatus",
    pool: "poolStatus",
    connections: "routeConnections",
    destinations: "routeDestinations",
    blocked: "routeBlockedHosts",
    blockedHosts: "routeBlockedHosts",
    health: "routeHealth",
    getRoutes: "routes",
    getRouteStatus: "routeStatus",
    getStatus: "status",
    getRouteHealth: "routeHealth",
    getHealth: "routeHealth",
    getRouteConnections: "routeConnections",
    getConnections: "routeConnections",
    getRouteDestinations: "routeDestinations",
    getDestinations: "routeDestinations",
    getRouteBlockedHosts: "routeBlockedHosts",
    getBlockedHosts: "routeBlockedHosts",
    getMetadata: "metadataStatus",
    getPool: "poolStatus",
  },
  // Shell: shorter aliases
  shell: {
    run: "runScript",
    script: "runScript",
    execute: "runScript",
    executeScript: "runScript",
    mysqlsh_run_script: "runScript",
    mysqlshRunScript: "runScript",
    upgrade: "checkUpgrade",
    dump: "dumpInstance",
    load: "loadDump",
    export: "exportTable",
    import: "importTable",
    importJSON: "importJson",
    import_json: "importJson",
    import_table: "importTable",
    export_table: "exportTable",
    dump_instance: "dumpInstance",
    load_dump: "loadDump",
    dumpSchema: "dumpSchemas",
    dumpTable: "dumpTables",
    importDump: "loadDump",
    restoreDump: "loadDump",
    get: "version",
    info: "version",
    status: "version",
  },
  // Introspection: shorter aliases
  introspection: {
    get: "dependencyGraph",
    sort: "topologicalSort",
    cascade: "cascadeSimulator",
    snapshot: "schemaSnapshot",
    constraints: "constraintAnalysis",
    risks: "migrationRisks",
  },
  // Core: shorter aliases
  core: {
    get: "readQuery",
    query: "readQuery",
    insert: "writeQuery",
    update: "writeQuery",
    delete: "writeQuery",
    list: "listTables",
    describe: "describeTable",
    create: "createTable",
    drop: "dropTable",
    indexCreate: "createIndex",
    indexes: "getIndexes",
    listIndexes: "getIndexes",
    showIndexes: "getIndexes",
    versioning: "enableVersioning",
    unversioning: "disableVersioning",
    disableVersion: "disableVersioning",
    removeVersioning: "disableVersioning",
    getVersion: "checkVersion",
    version: "checkVersion",
    condUpdate: "conditionalUpdate",
    updateConditionally: "conditionalUpdate",
    updateVersion: "conditionalUpdate",
  },
  // ProxySQL: shorter and intuitive aliases
  proxysql: {
    proxysql_status: "status",
    proxysql_runtime_status: "runtimeStatus",
    proxysql_servers: "servers",
    proxysql_connection_pool: "connectionPool",
    proxysql_query_rules: "queryRules",
    proxysql_query_digest: "queryDigest",
    proxysql_commands: "commands",
    proxysql_users: "users",
    proxysql_global_variables: "globalVariables",
    proxysql_process_list: "processList",
    proxysql_memory_stats: "memoryStats",
    proxysqlCommands: "commands",
    proxysqlProcessList: "processList",
    get: "status",
    rules: "queryRules",
    pool: "connectionPool",
    digest: "queryDigest",
    variables: "globalVariables",
    stats: "memoryStats",
    memory: "memoryStats",
    runtime: "runtimeStatus",
  },
};
