import fs from "node:fs";
import path from "node:path";

export default async function globalTeardown() {
  const rootDir = process.cwd();
  
  // Clean up common test artifacts generated by SystemDb and Audit logging
  const artifacts = [
    "test.sqlite",
    "test.sqlite-shm",
    "test.sqlite-wal",
    "test.jsonl",
    "test-metrics-registry.sqlite",
    "test-metrics-registry.sqlite-shm",
    "test-metrics-registry.sqlite-wal",
    "test-system.sqlite",
    "test-system.sqlite-shm",
    "test-system.sqlite-wal",
  ];

  for (const file of artifacts) {
    const filePath = path.join(rootDir, file);
    try {
      if (fs.existsSync(filePath)) {
        fs.rmSync(filePath, { force: true, maxRetries: 10, retryDelay: 500 });
        console.log(`[teardown] Cleaned up test artifact: ${file}`);
      }
    } catch (e) {
      console.warn(`[teardown] Failed to clean up ${file}:`, e);
    }
  }
}
